version: "3"
services:
  control-node:
    build:
      context: .
      dockerfile: Dockerfile
    image: ansible-node
    container_name: control-node
    networks:
      - ansible
    ports:
      - 2222:22
  node1:
    image: ansible-node
    container_name: node1
    networks:
      - ansible
    depends_on:
      - control-node
  node2:
    image: ansible-node
    container_name: node2
    networks:
      - ansible
    depends_on:
      - control-node
networks:
  ansible:
    driver: bridge
